[project]
name = "cantuccio"
version = "0.1.1"
description = "The sweetest corner plot package around."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.3.1",
    "isort>=8.0.1",
    "jax>=0.8.3",
    "kdexpress>=1.0.1",
    "matplotlib>=3.10.9",
    "mypy>=2.0.0",
    "scipy>=1.17.1",
]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "pytest>=9.0.3",
]
docs = [
    "marimo>=0.23.5",
    "myst-parser>=5.1.0",
    "nbsphinx>=0.9.8",
    "sphinx>=8.5.0",
    "sphinx-autodoc-typehints>=3.10.2",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.1.0",
]
